### ISSUE TITLE
설정창의 스케일을 줄이거나 늘릴경우와 옮길경우 비정상적인 애니메이션이 보여짐

### ISSUE THREAD

**Issue by SaidBySolo** [organization/alspotron#112]
## 정보

OS: Windows 10
버전: Alspostron 0.9.2

## 재현 방법

https://github.com/organization/alspotron/assets/33891531/dd929892-3af0-4bba-a4c3-ce5d3074394b

재현 방법은 영상과 같습니다.

추가로 필요하신 정보가 있다면 말씀해주시면 제공해드리겠습니다.

감사합니다.

**Comment by JellyBrick** [comment]
Windows 10/11의 내부 버그입니다. 해결할 수 없습니다. 

https://github.com/NyaomiDEV/Glasstron/issues/59
https://github.com/seo-rii/electron-acrylic-window/discussions/69
