### ISSUE TITLE
Alspotron이 많은 CPU 자원을 점유합니다.

### ISSUE THREAD

**Issue by SaidBySolo** [organization/alspotron#113]
## 정보

OS: Windows 10
버전: Alspostron 0.9.2

## 설명

![image](https://github.com/organization/alspotron/assets/33891531/b157b965-8708-4e38-9a34-83fc8f0ceb3e)

사진과 같이 평균적으로 20이상의 자원을 사용하고있습니다.

![image](https://github.com/organization/alspotron/assets/33891531/39bea2fa-f3e0-4a5d-a469-549776879577)

계속 창이 떠있는 가사 창 쪽에 개발자 도구를 킨 후 프로파일링 해보았을때 다음 [인터벌 함수가](https://github.com/organization/alspotron/blob/7807b65a1436e5befe9829bc60150479b0a1589e/renderer/components/PlayingInfoProvider.tsx#L89-L93) 가 지속적으로 호출 되는것을 확인 할 수 있었으나 해당 함수가 성능에 영향을 끼치는지는 확실하지 않은것같습니다.

**Comment by JellyBrick** [comment]
![image](https://github.com/organization/alspotron/assets/16558115/19a732e7-18d8-47c5-89be-be0e6e7a8d3a)


일단 제 PC에서는 문제가 확인되지 않는데,

1. 혹시 DevTools를 사용 중이신가요? 'DevTools를 켰을 때만' CPU 사용량이 높다면 정상입니다. (Electron 문제로 추정됨)
2. 사용자 CSS를 사용 중인가요? 사용자 CSS를 사용하시는 중이라면, 어떤 CSS인지 알 수 있을까요?
3. PC의 사양을 알 수 있을까요?

**Comment by SaidBySolo** [comment]
1. DevTools를 사용하지 않고있습니다.
2. 사용하지 않고 있습니다.
3.  사양 은 다음과 같습니다.
    *  CPU: i5-6500
    *  Ram: 8GB
    *  GPU: GTX 750ti

**Comment by SaidBySolo** [comment]
> * 0.10.1에서도 동일한 문제가 발생하나요?

마지막으로 사용했을때는 재현되지 않았습니다.

**Comment by JellyBrick** [comment]
일단 close합니다. 문제가 재발하거나, 원인이 확인 된 경우 reopen합니다
