### ISSUE TITLE
가사 싱크 밀림 문제

### ISSUE THREAD

**Issue by hyumsuk** [organization/alspotron#1132]
최신 버전으로 업데이트 이후 가사 싱크를 3초 단위로 인식해서 넘어갑니다.

https://github.com/user-attachments/assets/709f2398-1882-47a3-ae51-6fb58c79bd2b

**Comment by JellyBrick** [comment]
원인: https://github.com/organization/alspotron/blob/a941578cfbef765344bfdcf9c9a1d2b75f599fce/renderer/components/PlayingInfoProvider.tsx#L140

최신 버전에서, progress를 보간해주는 코드가 삭제되어 발생한 문제입니다. 해결 예정입니다.
