### ISSUE TITLE
Spotify와 동기화되지 않음

### ISSUE THREAD

**Issue by lHaneul** [organization/alspotron#1224]
밑의 가사 싱크 문제와 같은 문제가 있어서 글 씁니다

스포티파이를 최소화 상태나 백그라운드에 두었을 때,
3초마다 싱크가 되는 상황에서 종종 현재 진행 상황을 불러오지 못하는 경우가 생깁니다.
거의 1분 정도 기다리면 그제야 정보 갱신이 되거나, 스포티파이 프로그램을 다시 화면에 띄워야 정보를 갱신합니다

**Comment by JellyBrick** [comment]
Spicetify의 버그로 추정됩니다.

**Comment by JellyBrick** [comment]
Duplicate of #1132 

원인은 https://github.com/organization/alspotron/issues/1132#issuecomment-2431673283 코멘트를 참고하세요.

**Comment by Ingan121** [comment]
스포티파이 실행 인자에 `--disable-backgrounding-occluded-windows` 추가하면 창을 최소화하지 않는 이상 동기화가 계속 유지됩니다.

Alspotron 최신 버전에서 싱크는 보간이 적용돼서 멈추는 일은 없어졌지만 현재 재생중인 곡 정보 갱신이 안되는 경우가 있는데 이럴 때 사용해보세요.
