### ISSUE TITLE
[Bug]: Spicetify Extension에서 종종 pause 이벤트를 전송하지 않음

### ISSUE THREAD

**Issue by gkrtn72** [organization/alspotron#1246]
노래를 일시정지 했는데 가사는 계속 나옵니다

https://github.com/user-attachments/assets/6d3f578d-a20f-46d2-8732-fc15589d33b2

**Comment by RaraHan** [comment]
동일증상 발생중입니다

**Comment by alvin0319** [comment]
@RaraHan @gkrtn72 사용중이신 Spotify, Spicetify 버전 기재 부탁드리겠습니다.

**Comment by gkrtn72** [comment]
@alvin0319 
Windows(64비트)용 Spotify
1.2.51.345.gcc39d911
Spicetify v2.38.4

**Comment by RaraHan** [comment]
Windows(64비트)용 Spotify
1.2.51.345.gcc39d911
Spicetify v2.38.4
Theme: marketplace
Extensions: alspotron.js   /////////[Alspotron-Web-Setup-0.23.1.exe]
Custom apps: marketplace

추가
1. Alspotron 재부팅시 가사 테마 리셋됩니다. (매번 실행시 저장한 테마 파일 불러와야 합니다), 
(좌측 메뉴 창 > 테마 목록 > 테마 설정 > 재부팅해도 선택한 테마 이름 저장되나, 
![image](https://github.com/user-attachments/assets/56c78523-d615-4718-81d8-8a9b67d0a26f)

좌측 메뉴 테마 > 사용 가능한 테마 이곳이 매번 리셋되어 날아갑니다)
![image](https://github.com/user-attachments/assets/5ef9b479-f111-4f5d-9b0a-56d7e537c692)

2. 마우스 근접시 투명화 기능 마우스 근접시 투명도 복원되지않고 중복적 투명화 되어 매우 투명하게 유지됩니다.

**Comment by RaraHan** [comment]
> @RaraHan @gkrtn72 사용중이신 Spotify, Spicetify 버전 기재 부탁드리겠습니다.

Windows(64비트)용 Spotify
1.2.51.345.gcc39d911
Spicetify v2.38.4
Theme: marketplace
Extensions: alspotron.js   /////////[Alspotron-Web-Setup-0.23.1.exe]
Custom apps: marketplace

추가
1. Alspotron 재부팅시 가사 테마 리셋됩니다. (매번 실행시 저장한 테마 파일 불러와야 합니다), 
(좌측 메뉴 창 > 테마 목록 > 테마 설정 > 재부팅해도 선택한 테마 이름 저장되나, 
![image](https://github.com/user-attachments/assets/56c78523-d615-4718-81d8-8a9b67d0a26f)

좌측 메뉴 테마 > 사용 가능한 테마 이곳이 매번 리셋되어 날아갑니다)
![image](https://github.com/user-attachments/assets/5ef9b479-f111-4f5d-9b0a-56d7e537c692)

2. 마우스 근접시 투명화 기능 마우스 근접시 투명도 복원되지않고 중복적 투명화 되어 매우 투명하게 유지됩니다.

**Comment by JellyBrick** [comment]
@RaraHan
> 마우스 근접시 투명화 기능 마우스 근접시 투명도 복원되지않고 중복적 투명화 되어 매우 투명하게 유지됩니다.
#208 을 말씀하신걸까요?

**Comment by RaraHan** [comment]
> @RaraHan
> 
> > 마우스 근접시 투명화 기능 마우스 근접시 투명도 복원되지않고 중복적 투명화 되어 매우 투명하게 유지됩니다.
> 
> #208 을 말씀하신걸까요?

조금 다릅니다.  

EX) 커서 근접 불투명도 50%정도 설정후   
마우스 올리면 50% > 내리면 100%로 복원이 되어야 하는데 
그대로 50%유지 > 다시 마우스 올리면 유지돈 50%에서 +50%되어 약 25%? 느낌으로 더욱 투명하게 유지됩니다.

// 단순 버그같기도 합니다 재부팅 하니 일단 정상 작동 합니다.
//저상황은 간혹 나옵니다.


추가로 
가사를 화면 중앙에 배치후 테스트 하였을때
마우스 커서 불투명 50% 설정

마우스 올린후 

가사 좌 우로 마우스 빠져나오면 원복 100% (불투명 100%)
가사 위 아래로 마우스 빠져나오면 원복 안되고 투명도 유지됩니다 (50% 설정값으로)

원복하려면 다시 마우스 좌,우에서 올린후 좌우로 빠져나오면 불투명하게 복원됩니다.

**Comment by Su-Yong** [comment]
해당 문제는 #208 해결을 위해 임의로 넣었던 패치때문에 생긴문제로 보입니다. #208 이슈는, Windows에선 마우스 근접 불투명도가 제대로 동작하지 않는 문제가 있었는데 이를 해결하기 위해 임의로 제가 마우스 이벤트 관련 패치를 넣었습니다.

이부분은 electron에서 버그를 해결하기까지는 어쩔수 없는 부분입니다. 하지만 많은사람들이 불편을 요하는걸로 보아서 일단 해당 기능을 기본으로 꺼버리고, 실험적 기능으로 "Windows에서 근접 마우스 사용 고침" 옵션을 넣는 방향으로 일단 수정하도록 하겠습니다.

혹시 더 좋은 개선방안이 있다면 적어주시면 감사하겠습니다

**Comment by HelloWorld017** [comment]
현재 TunaOBS Zod Schema 가 다음과 같이 정의되어 있는데, Spicetify Extension 에서는 `stopped` 로 보내고 있습니다.
```ts
  status: z.union([
    z.literal('playing'),
    z.literal('paused'),
    z.literal('idle'),
  ]),
```

따라서 401 Unauthorized 응답을 받아서 재생상태가 업데이트 되지 않고 있는 듯 합니다.

**Comment by HelloWorld017** [comment]
```diff
     if (!Spicetify.Player.isPlaying()) {
-      info.status = 'stopped';
+      info.status = 'paused';
       return info;
     }
```

위 diff로 해결했습니다.
