### ISSUE TITLE
재부팅 시 테마 / 가사 초기화 문제

### ISSUE THREAD

**Issue by lHaneul** [organization/alspotron#1279]
잘 사용하고 있습니다!

재부팅할 때 기존에 불러온 테마 파일과 고급 검색에서 설정해놓은 가사가 초기화되는 문제가 있는 것 같습니다.

AppData\Roaming\alspotron 경로 내의 lyrics.json 파일과 theme 폴더 내의 파일이 재부팅 시 지워지거나 초기화되고 있어서

혹시 제 컴퓨터만의 문제일까요?

**Comment by Su-Yong** [comment]
사용하고 있는 버전을 알수 있을까요?
또 windows의 경우 web-setup이 아닌 exe파일은 그냥 포터블 버전이라 상태 저장이 안될수도 있습니다. 확실하게 재현은 안되긴하네요

**Comment by lHaneul** [comment]
0.23.1 사용하고 있습니다!
포터블이 아닌 web-setup 사용해서 설치한 상황입니다
프로그램 / 플러그인 / 관련 폴더 모두 제거하고 다시 설치해본 뒤 오류 있으면 다시 글 남기겠습니다

**Comment by lHaneul** [comment]
이유는 모르겠으나.. 0.23 버전 설치 후 기존 테마 파일을 불러온 후 버전을 올리니 정상적으로 작동합니다

**Comment by kms0219kms** [comment]
저도 동일한 이슈를 겪고 있습니다.
어제 설치한 latest 버전이고, 윈도우 11 26100.2161 입니다.

**Comment by JellyBrick** [comment]
@Su-Yong 재현 방법

https://github.com/organization/alspotron/issues/1246#issuecomment-2496509832

참고

**Comment by Su-Yong** [comment]
@kms0219kms @lHaneul 답변이 늦어서 죄송합니다. 혹시 증상 발현되시는분은 `config.json`, `lyrics.json` 그리고 `theme` 폴더 총 3가지 파일 및 폴더를 첨부해주실수 있을까요? 만약 첨부가안되면 me@suyong.me 해당 이메일로 파일 전송 부탁드립니다.

![image](https://github.com/user-attachments/assets/c02b2be7-af4f-4949-a6dc-82d8ff377f73)

해당 파일은 사진에 보이는 위치(사용자 이름은 바뀝니다)에 있으며 `%appdata%\alspotron`위치에 있습니다.
해당 위치를 바로 여시려면
1. `win` + `r`키를 눌러 아래 사진과 같은 창을 엽니다
	![image](https://github.com/user-attachments/assets/4ef58cf6-539a-475b-8808-205695270c07)
2. `%appdata%\alspotron`을 입력하고 확인을 누르면 사진처럼 파일이 보관된 위치가 보입니다.
	![image](https://github.com/user-attachments/assets/a5b08732-301b-4b92-9cd5-2e16b80d0fd4)
	```
	%appdata%\alspotron
	```

**Comment by kms0219kms** [comment]
[alspotron.zip](https://github.com/user-attachments/files/17967896/alspotron.zip)
@Su-Yong

**Comment by HelloWorld017** [comment]
제 기기에서 재현 성공해서 PR 오픈했습니다.
