### ISSUE TITLE
가사 선택창에서 가사 비활성화 선택

### ISSUE THREAD

**Issue by limtaehyuns** [organization/alspotron#1287]
![screen-capture-2024-11-25-18-21-57PM](https://github.com/user-attachments/assets/1ddad665-674b-475e-a0e7-85d763814e94)

해당 선택 창에서 일치하는 가사가 없을시에는 아예 노출하지 않도록 설정이 버튼이 추가되었으면 좋겠습니다.

**Comment by JellyBrick** [comment]
간단 검색 창에 기타 기능 버튼을 추가할 경우 버튼이 과도하게 많아지는 문제가 있어서, (필수 기능을 제외한 나머지 기능 버튼은) 고급 검색 창으로 빼둔 상태입니다. 더 좋은 아이디어가 있으시면 말씀해주시면 감사하겠습니다

**Comment by limtaehyuns** [comment]
![screen-capture-2024-11-25-19-23-58PM@2x](https://github.com/user-attachments/assets/7b38203f-6a14-4285-b877-5d2970a86c1b)
@JellyBrick 해당 위치에 작게 아이콘을 추가하고, 누를시 가사 비노출이 되게 되면 좋을 것 같습니다.
또는 전원 버튼을 드롭다운식으로 아예 종료하기, 가사 비노출하기 와 같은 형식으로 변경되는것도 좋아보입니다.

**Comment by Su-Yong** [comment]
> @JellyBrick 해당 위치에 작게 아이콘을 추가하고, 누를시 가사 비노출이 되게 되면 좋을 것 같습니다. 또는 전원 버튼을 드롭다운식으로 아예 종료하기, 가사 비노출하기 와 같은 형식으로 변경되는것도 좋아보입니다.

![image](https://github.com/user-attachments/assets/06cbfea3-82eb-4bc5-ac61-dc74e8e9ce6b)
해당 부분은 사실 개발자 모드를 키면 나오는 버튼창이긴합니다. 말씀드린것처럼 전원버튼 대신, 드롭다운이나 하위에 변경 옵션을 따로 dropdown으로 두는등의 방안을 생각해보겠습니다

**Comment by limtaehyuns** [comment]
@JellyBrick 오 또는 Alspotron 로고를 클릭하면 안뜨게 하는것도 좋겠네요

**Comment by Su-Yong** [comment]
resolved at #1316
