### ISSUE TITLE
Spicetify 업데이트 후 작동 안합니다.

### ISSUE THREAD

**Issue by RaraHan** [organization/alspotron#1327]
Windows(64비트)용 Spotify
1.2.52.442.g01893f92
Spicetify v2.38.5

Spicetify 업데이트 후 작동 안합니다.
[alspotron] 0.23.1

**Comment by JellyBrick** [comment]
https://github.com/organization/alspotron#installation 참고하여 alspotron extension 재설치 부탁드립니다
