### ISSUE TITLE
0.24.0 엔비디아 성능 오버레이 사용시 창 가림 현상 발생

### ISSUE THREAD

**Issue by PILLAR777** [organization/alspotron#1352]
창 가림 현상 문제 해결  켜도 안되네요 기능적으로 겹쳐서 그런걸까요? 이전버전에선 문제 없었는데

**Comment by JellyBrick** [comment]
혹시 문제와 관련된 스크린샷이 있다면 올려주실 수 있으신가요?

**Comment by PILLAR777** [comment]
> 혹시 문제와 관련된 스크린샷이 있다면 올려주실 수 있으신가요?



![오버레이 끔](https://github.com/user-attachments/assets/acb348ca-202e-45cf-aa7a-a2c39e765f9f)

이게 NVIDIA 오버레이를 끈 상태에서입니다. 이럴땐 정상적으로 가사창이 최상단 고정이라 잘 나옵니다

![오버레이 키고 상단 해결 킴](https://github.com/user-attachments/assets/060ba529-50c9-4506-b880-a0f7d127649a)

이건 NVIDAI 오버레이를 킨 상태에서입니다. 상단 창가림 해결 킨 상태이고, 해결을 끄나 키나 똑같습니다..

그 외에 어떤식으로 스크린샷을 찍어야할지는 잘 모르겠습니다. 알려주신다면 그대로 찍어볼게요.

**Comment by Su-Yong** [comment]
NVidia가 항상 최상위로 유지하려고 해서 alspotron이 강제로 최상위로 끌어 올리려고 해도 안되는것 같습니다. 창 가림 현상 현상 해결은, nvidia프로그램이 아니라, windows 24H2 버전 이후로 발생한 이슈를 해결하는 옵션이여서 적용이 안되는듯 합니다

**Comment by PILLAR777** [comment]
> NVidia가 항상 최상위로 유지하려고 해서 alspotron이 강제로 최상위로 끌어 올리려고 해도 안되는것 같습니다. 창 가림 현상 현상 해결은, nvidia프로그램이 아니라, windows 24H2 버전 이후로 발생한 이슈를 해결하는 옵션이여서 적용이 안되는듯 합니다

확인했습니다. 엔비디아 실시간 녹화가 안되는건 아쉽지만 ,  괜찮아요. 나중에 해결 된다면 알려주세요!
CLOSE 해도 괜찮습니다 !

**Comment by PILLAR777** [comment]
CLOSE
