### ISSUE TITLE
Multiple lyric platform

### ISSUE THREAD

**Issue by JellyBrick** [organization/alspotron#144]
e.g. Musixmatch

**Comment by Su-Yong** [comment]
releate https://github.com/organization/alspotron/commit/fb6cd47f70d9ad79a054ef93bf0c8640d183c66b

**Comment by Su-Yong** [comment]
지원예정인 가사 제공자
- [X] Default
- [ ] Spotify
- [ ] Youtube Music

**Comment by Su-Yong** [comment]
view [feature/lyric-provider](https://github.com/organization/alspotron/tree/feature/lyric-provider)
