### ISSUE TITLE
macOS: 어플리케이션 전환 UI 및 독에서 가리기

### ISSUE THREAD

**Issue by HelloWorld017** [organization/alspotron#20]
현재 어플리케이션 전환 UI 및 독에서 표시되는 것으로 보이나, 가릴 수 있으면 좋을 것 같습니다.

**Comment by smnis** [comment]
설정이랑 가사선택 window에 대한 이슈인 것 같은데 꼭 가려야 할까요? 앞으로 설정창에 계속 기능이 추가된다면 지금처럼 보이게 하는게 사용자 경험상 더 좋다고 생각합니다.

만약 가려야 한다면 `mainWindow`처럼 `hiddenInMissionControl`를 `true`로 주면 가려지긴 하는데 그보단 `blur` 이벤트에 `close()`를 호출하는 방식이 다른 이슈 여지를 줄일 수 있을 것 같습니다.

**Comment by HelloWorld017** [comment]
설정 및 가사선택은 당연히 표시되는게 맞으나, 가사표시창이 떠있는 이슈라서 더 확인해봐야할 것 같습니다.

**Comment by JellyBrick** [comment]
> 설정 및 가사선택은 당연히 표시되는게 맞으나, 가사표시창이 떠있는 이슈라서 더 확인해봐야할 것 같습니다.

@HelloWorld017 혹시 https://github.com/organization/alspotron/commit/bc2a497e0c9f5c0863bf219aae8b03883d24dfbb 버전에서도 오류가 발생하시나요?

**Comment by HelloWorld017** [comment]
재현 안되는 것 확인했습니다! 감사합니다 🙇
