### ISSUE TITLE
Spotify lyrics are replaced by Alsong lyrics

### ISSUE THREAD

**Issue by alvin0319** [organization/alspotron#212]
With 3739f8653729e6ba5cbaa4af74b5fc852fe22813, Spotify's internal lyrics are now sent over request with the initial 'playing' request, but alspotron only shows Alsong lyrics regardless of lyrics are provided.

The Spotify internal lyrics should be prioritized over Alsong's unless the user specified lyrics with Lyrics Finder.

**Comment by JellyBrick** [comment]
This is the intended behavior. Alspotron shows `alsong`'s lyric when possible, because lyrics sent from `Spotify` often don't include translations.
