### ISSUE TITLE
Electron Updater가 비직관적으로 동작함

### ISSUE THREAD

**Issue by Su-Yong** [organization/alspotron#242]
1. 업데이트 무시 기능이 존재하지 않음
2. 업데이트 진행 중 표시 프로그래스바가 움직이지 않음
3. 업데이트 확인 로직과 업데이트를 할지 물어보는 로직이 합쳐져있음

**Comment by JellyBrick** [comment]
https://github.com/organization/alspotron/commit/5d0518a4966c72768cf6da53158435c5c11d4efc

로 완화
