### ISSUE TITLE
가사 선택이 한번에 안 됨

### ISSUE THREAD

**Issue by JellyBrick** [organization/alspotron#251]
컴포넌트를 두번씩 클릭해야 적용됨

![bug-optimize](https://github.com/organization/alspotron/assets/16558115/d6c7fd9c-cef6-4a38-8f9b-8426674144d2)

# 재현 단계

- A를 클릭
- B를 클릭
- A 가사가 적용됨
- B를 클릭
- B를 클릭
- B 가사가 적용됨

# 정상 동작

- A를 클릭
- A 가사가 적용됨
- B를 클릭
- B 가사가 적용됨

**Comment by Su-Yong** [comment]
resolved by f34f188
