### ISSUE TITLE
뒤로가기 버튼이 프로덕션 환경에서 동작하지 않음

### ISSUE THREAD

**Issue by Su-Yong** [organization/alspotron#252]
# 증상
- 뒤로가기 버튼을 누르면 항상 첫번째 페이지로 돌아감

# 원인
- `@solid/router` 문제로 추정됨

# 해결방법
- 라우터 방식을 변경함 (메모리, 해시등)

**Comment by JellyBrick** [comment]
![image](https://github.com/organization/alspotron/assets/16558115/a9ef4b0e-56c6-4178-b614-15fd0b784782)

올바르지 않은 href가 입력됨

**Comment by Su-Yong** [comment]
- Provider.tsx
```ts
      <Router source={hashIntegration()}>
        {props.children}
      </Router>
```

이렇게 hash 라우팅 방식을 이용하면 문제가 해결됨
