### ISSUE TITLE
Alspotron does not work with Spotify version 1.2.17 or later in macOS

### ISSUE THREAD

**Issue by kms0219kms** [organization/alspotron#276]
스포티파이 1.2.17 버전 이상부터 스포티파이의 구조 변경으로 Alspotron 확장프로그램이 작동하지 않습니다.
Starting with Spotify version 1.2.17 and higher, the Alspotron extension does not work due to changes in Spotify's structure.

## 재현 (Reappearance)
현재 최신 버전인 1.2.20 이상 설치 후 Alspotron 이용 시 확인 가능 (macOS)
You can check this by using Alspotron after installing the latest version 1.2.20 or higher in macOS.

<img width="1291" alt="Screenshot 2023-09-24 at 12 35 43 PM" src="https://github.com/organization/alspotron/assets/67222970/fefe07f3-1b63-4066-a826-0c905f7d291b">

## Spotify Version Information
macOS(Apple Silicon)용 Spotify
1.2.20.1218.g02aff7a4
Spicetify v2.23.2
Theme:
Extensions: alspotron.js
Custom apps:

**Comment by alvin0319** [comment]
![image](https://github.com/organization/alspotron/assets/32565818/b6241378-257d-4331-8222-e26c7fdb3fb2)
Spicetify 2.23.2, Spotify 1.2.20.1218.g02aff7a4 (win)에서 작동 확인됩니다.

```cmd
spicetify backup apply
```
명령어를 통해 백업본을 불러오거나, extension을 제거했다가 재 적용하고 확인해주세요.

```cmd
spicetify config extensions alspotron.js-
spicetify apply
spicetify config extensions alspotron.js
```

**Comment by kms0219kms** [comment]
backup apply, config에서 제거 후 재적용 모두 동일합니다.

**Comment by kms0219kms** [comment]
➜  ~ spicetify config extensions alspotron.js-
success Config changed: extensions = 
info Run "spicetify apply" to apply new config

➜  ~ spicetify apply
spicetify v2.23.2
note Full Spicetify functionality is not guaranteed above Spotify's v1.2.17
info Spicetify up-to-date
Overwriting raw assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
success Spotify is spiced up!

➜  ~ spicetify config extensions alspotron.js
success Config changed: extensions = alspotron.js
info Run "spicetify apply" to apply new config

➜  ~ spicetify apply
spicetify v2.23.2
note Full Spicetify functionality is not guaranteed above Spotify's v1.2.17
info Spicetify up-to-date
Overwriting raw assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
Transferring extensions:
OK
success Spotify is spiced up!

**Comment by alvin0319** [comment]
```cmd
spicetify enable-devtools
```
로 개발자 도구 활성화 한 다음, `ctrl + shift + i` (`cmd + shift + i`)를 통해 개발자도구를 열고, Network 탭에서 localhost로 요청 보내지나 확인해주세요

혹은, Console 탭에서 관련 오류가 발생하나 확인해주세요. (Spicetify에서 BC Breaking 패치가 있었던것은 확인되었으나, 아직 호환성 패치로 남아있는것을 확인했습니다.)

**Comment by kms0219kms** [comment]
<img width="1712" alt="Screenshot 2023-09-24 at 1 07 00 PM" src="https://github.com/organization/alspotron/assets/67222970/036fee85-2664-4af3-9a85-2ae9ce39f04c">
<img width="1712" alt="Screenshot 2023-09-24 at 1 07 12 PM" src="https://github.com/organization/alspotron/assets/67222970/85f10e0a-ff6b-47c6-a02f-6db628b94649">

**Comment by kms0219kms** [comment]
요청하지 않는 것으로 보입니다.

**Comment by kms0219kms** [comment]
<img width="1712" alt="Screenshot 2023-09-24 at 1 07 45 PM" src="https://github.com/organization/alspotron/assets/67222970/c473137e-0ed9-467a-9c4a-deb116e40841">
alspotron.js 에서 Uncaught SyntaxError: Invalid or unexpected token 가 나오는 것을 확인했습니다.

**Comment by kms0219kms** [comment]
원인을 알았습니다.
DownGit이나 GitHub raw로 다운로드를 받으니 이상하게도 Uncaught SyntaxError: Invalid or unexpected token이 나오는 것을 확인했습니다.
Jsdelivr CDN을 curl하게 했더니 오류가 사라졌습니다.
```
curl https://cdn.jsdelivr.net/gh/organization/alspotron@master/extensions/alspotron.js -o alspotron.js
```
