### ISSUE TITLE
가사 표시에 `ellipsis` 설정할 수 있게 하는 옵션 필요

### ISSUE THREAD

**Issue by JellyBrick** [organization/alspotron#33]
![image](https://github.com/organization/alspotron/assets/16558115/f8a8ca5f-6b90-497d-8abb-59d15261c7b0)

**Comment by Su-Yong** [comment]
일단 Marquee는 적용하면 안되는것으로 확정

**Comment by JellyBrick** [comment]
https://github.com/organization/alspotron/assets/16558115/bc3ab789-07bb-4dc4-9356-55be39afcc8a

Marquee 적용시
