### ISSUE TITLE
설정 창을 전체화면으로 전환 후 원래 크기로 돌아갈 수 없음

### ISSUE THREAD

**Issue by alvin0319** [organization/alspotron#38]
<img width="91" alt="image" src="https://github.com/organization/alspotron/assets/32565818/3d7481e5-8dca-4742-b316-b0c8b13ea3e3">

해당 버튼으로 설정창을 전체화면으로 전환 후, 원래 크기로 돌아갈 수 없음. (설정 창을 닫거나, 창을 마우스로 끌어내려 원래 크기로 전환은 가능)

**Comment by JellyBrick** [comment]
fixed at 228ec5cd38d649b00cdda6d55ec2a84682ce7512
