### ISSUE TITLE
스포티파이에서 가사를 제공하지 않는 곡에서 '플레이어 제공 가사'를 선택하면 가사 표시기가 업데이트되지 않음 

### ISSUE THREAD

**Issue by star0202** [organization/alspotron#387]
## 재현
스포티파이에서 가사를 제공하지 않는 곡 A 재생
가사 선택 메뉴에서 '플레이어 제공 가사' 선택
다른 곡 B 재생

## 예상되는 동작
가사 표시기가 곡 B의 가사를 표시함

## 실제 동작
가사 표시기가 곡 A의 가사(알송 가사가 있는 경우에만, 없다면 빈 공간)를 유지함

## 버전
Spotify for Windows (64 bit) 1.2.22.982.g794acc0a
Spicetify v2.25.3
Windows 11 Pro 22H2 (22621.2428)
Alspotron 0.16.4

**Comment by Su-Yong** [comment]
rersolved at https://github.com/organization/alspotron/commit/fb6cd47f70d9ad79a054ef93bf0c8640d183c66b
