### ISSUE TITLE
arm64 빌드 실행 안됨

### ISSUE THREAD

**Issue by smnis** [organization/alspotron#46]
<img width="372" alt="스크린샷 2023-07-09 오후 12 48 30" src="https://github.com/organization/alspotron/assets/13712304/d5a037e4-3a25-46ca-b7c0-d38c6f1c15b6">

## Machine
* 2021 MacBook Pro 14
* M1 Pro
* macOS Ventura 13.4.1(22F82)

**Comment by JellyBrick** [comment]
https://github.com/th-ch/youtube-music#macos
https://github.com/organization/alspotron#macos

참고하여 기존 버전 삭제 후 설치하면 정상 동작함을 확인
