### ISSUE TITLE
선택한 가사 초기화 기능 추가

### ISSUE THREAD

**Issue by JellyBrick** [organization/alspotron#6]
![image](https://github.com/organization/alspotron/assets/16558115/c81931a6-f6eb-4bb4-857d-adcc18b56486)

- 해당 영역 클릭시 가사 초기화 되는 기능 나오게 하면 될듯

**Comment by Su-Yong** [comment]
resolved by 51ef2f897a86d02d52b8db77dcbdd1ad0fd4629f
