### ISSUE TITLE
스포티파이에서 가사를 제공하는 곡에서 '플레이어 제공 가사'를 선택하면 가사 표시가 안됨

### ISSUE THREAD

**Issue by rkdrlgh22** [organization/alspotron#707]
스포티파이에서 가사를 제공하는 곡이지만 "플레이어 제공 가사" 로바꿀시 업데이트가 안되고 N/A 로 출력이 안나옵니다.
그뿐만 아니라 가사 선택을 마우스로 드래그 하면 프레임드랍이 걸리면서 드래그 속도가 느려지고 프로그램이 급격하게 무거워집니다.

**Comment by rkdrlgh22** [comment]
프로그램이 작동이 플레이어 제공 가사가 spotify에서 작동이 안될떄 Client ID 나 Client secret 으로 수동으로 추가해서 가사를 불러오게 하는 방법도 고려해주세요.

**Comment by Su-Yong** [comment]
> 스포티파이에서 가사를 제공하는 곡이지만 "플레이어 제공 가사" 로바꿀시 업데이트가 안되고 N/A 로 출력이 안나옵니다. 그뿐만 아니라 가사 선택을 마우스로 드래그 하면 프레임드랍이 걸리면서 드래그 속도가 느려지고 프로그램이 급격하게 무거워집니다.

가사선택창을 마우스로 드래그해서 창을 이동하게되면 급격한 프레임드랍이 일어나는 문제는 윈도우 버그입니다. 윈도우 최신 업데이트를 해주시면 해당 문제가 사라집니다. (Windows 11 23H2 22631.3155 기준 해결됨)

추가로 댓글달아주신 Spotify API를 이용하는 부분은 [해당 이슈](https://github.com/organization/alspotron/issues/144#issuecomment-1964529605)에 배정해두겠습니다

**Comment by JellyBrick** [comment]
cc @alvin0319 @HelloWorld017

**Comment by Su-Yong** [comment]
https://github.com/spicetify/spicetify-cli/issues/2837 현재 해결책은 스포티파이 클라이언트 버전을 낮추는거말곤 없다고합니다
