### ISSUE TITLE
일시정지시 가사 노출여부 선택

### ISSUE THREAD

**Issue by noeulnight** [organization/alspotron#724]
노래 재생을 일시정지 할 경우 오버레이가 보이지 않게 설정할수 있었으면 좋겠습니다!

**Comment by Su-Yong** [comment]
![image](https://github.com/organization/alspotron/assets/13764936/70a930a9-9d1a-4228-9031-9cf009c6d7fa)
위 사진과 같이 `설정` > `테마` > `가사 테마 설정` > `일시정지 시 투명도`를 0%로 설정하시면 가사가 보이지 않습니다.
마찬가지로 `Now Playing 테마 설정` > `일시정지 시 투명도`를 0%로 설정하시면 가사뿐만이 아니라 Now Playing 창도 일시정지시 보이지 않게 됩니다
