### ISSUE TITLE
업데이트 이후 실행 오류

### ISSUE THREAD

**Issue by khsopop0** [organization/alspotron#930]
![image](https://github.com/organization/alspotron/assets/102741762/aee525b1-c41c-412b-9cfb-72c60b64f38e)
Windows11을 이용하고 있는 사용자 입니다.
기존 Alspotron은 정상적으로 작동했으나, 이번 Alspotron-Web-Setup-0.20.2 버전에서 업데이트 진행 후 Alspotron 실행 시 다음과 같은 오류 메세지가 출력 됩니다.
오류 출력 이후, 기존 숨겨진 아이콘 표시 창에도 뜨지 않으며, 이후 스포티파이 실행 시에도 가사가 정상적으로 출력 되지 않습니다.

**Comment by Su-Yong** [comment]
해당 이슈 이미 발견하여 해결하려고 했으나, 생각보다 오래걸려 현재 릴리즈에선 내린 상태입니다 0.20.2버전이 아닌, 0.20.1버전을 사용해주시면 감사하겠습니다

**Comment by Su-Yong** [comment]
> 해당 이슈 이미 발견하여 해결하려고 했으나, 생각보다 오래걸려 현재 릴리즈에선 내린 상태입니다 0.20.2버전이 아닌, 0.20.1버전을 사용해주시면 감사하겠습니다

어제 릴리즈하고 바로 삭제했는데 그대로 릴리즈가 남아있어서 방금 릴리즈 내렸습니다 감사합니다
