### ISSUE TITLE
스포티파이에서 재생 인식 안됨

### ISSUE THREAD

**Issue by Yakamoz940** [organization/alspotron#979]
안녕하십니까
연초에 해당 소프트웨어를 알게 되어 정말 잘 사용하고 있습니다. 정말 감사드립니다.

평소처럼 그냥 스포티파이와 해당 소프트웨어를 시작 프로그램으로 등록한 상태로 사용하고 있었는데
해당 게시물을 작성 기점 일주일 내의 기간에서 가사가 표시가 안되는 것으로 확인이 되었습니다.

어떠한 정보를 더 제공해드려야 도움이 될지는 모르겠지만 최대한 아는 선에서 적겠습니다.

스포티파이에서 노래가 재생 중인데 노래 선택 옵션으로 가보면 
N/A - Not Playing
으로 표기되어 있으며 수동으로 아티스트명이나 노래 제목을 검색해서 가사를 선택해도 해당 선택한 가사가 표시 되지 않습니다.
동일 창에서 현재 적용된 가사 창에서도
N/A
로만 표기 되고 있습니다.

따라서 해본 조치로는 Alspotron 언인스톨, 공식 가이드에서 제공하는 방법으로 Spicetify 제거, 스포티파이 제거 이후 리부팅
스포티파이 설치, Spicetify 설치, Alspotron 설치 했으나 해당 문제가 동일합니다.

어떠한 방법으로 해결이 가능할까요?

다시금 말씀드리지만 정말 잘 사용하고 있습니다.

**Comment by alvin0319** [comment]
사용중인 OS, Spotify, Spicetify 버전이 어떻게 되시나요?

Win11
Spotify 1.2.40.599.g606b7f29
Spicetify v2.36.13

에서 잘 작동하는것 확인했습니다.

**Comment by Yakamoz940** [comment]
> 사용중인 OS, Spotify, Spicetify 버전이 어떻게 되시나요?
> 
> Win11 Spotify 1.2.40.599.g606b7f29 Spicetify v2.36.13
> 
> 에서 잘 작동하는것 확인했습니다.

Windows(64비트)용 Spotify
1.2.40.599.g606b7f29
Spicetify v2.36.13

입니다.

**Comment by alvin0319** [comment]
`spicetify enable-devtools`로 개발자 도구 활성화 후, 스포티파이에서 ctrl+shift+i, 개발자도구의 Network 탭에서 노래를 재생할 때 `localhost:1608`로 요청이 가는것이 보이나요?

![image](https://github.com/organization/alspotron/assets/32565818/d6da0403-99b3-4132-be2e-3228a7d6b4d7)

**Comment by Yakamoz940** [comment]
> `spicetify enable-devtools`로 개발자 도구 활성화 후, 스포티파이에서 ctrl+shift+i, 개발자도구의 Network 탭에서 노래를 재생할 때 `localhost:1608`로 요청이 가는것이 보이나요?
> 
> ![image](https://private-user-images.githubusercontent.com/32565818/343827572-d6da0403-99b3-4132-be2e-3228a7d6b4d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MDEwMjQsIm5iZiI6MTcxOTUwMDcyNCwicGF0aCI6Ii8zMjU2NTgxOC8zNDM4Mjc1NzItZDZkYTA0MDMtOTliMy00MTMyLWJlMmUtMzIyOGE3ZDZiNGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE1MDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMjgxMjJiNGEyZTg5YmJiZTMxODM2MmI3NzFkMmRhOTNmY2IxZjMyMTg1MTM4ZjFmY2RlOWE1YTQ1MzczZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.74Sty0MsfSSoMcz6J8XcIWKdvN1CTXY-rGIa2U2W3RY)

보이지 않습니다.

**Comment by alvin0319** [comment]
Alspotron 확장 삭제 후 다시 추가하시면 될 것 같습니다.

```bash
spicetify config extensions -alspotron.js
```
위 명령어로 확장 삭제 후 추가 명령어로 다시 추가하시고, apply 하시면 정상적으로 추가됩니다.

시도해보시고 잘 된다면 이슈 클로즈 부탁드리겠습니다.

**Comment by Yakamoz940** [comment]
> Alspotron 확장 삭제 후 다시 추가하시면 될 것 같습니다.
> 
> ```shell
> spicetify config extensions -alspotron.js
> ```
> 
> 위 명령어로 확장 삭제 후 추가 명령어로 다시 추가하시고, apply 하시면 정상적으로 추가됩니다.
> 
> 시도해보시고 잘 된다면 이슈 클로즈 부탁드리겠습니다.

감사합니다.
